export const Images = {
  logo: '/images/logo.png',
  googleIcon: '/images/google-icon.png',
  bgImg: '/images/bg-img.png',
  big_logo_icon: '/images/big_logo_icon.png',
  how_it_works: '/images/how_it_works.png',
  laptop_girl_image: '/images/laptop_girl_image.png',
  avatar: '/images/avatar.png',
  robot_image: '/images/robot_image.png',
  meeting_image: '/images/meeting_image.png',
  meeting_image_2: '/images/meeting_image_2.png',
  man_image: '/images/man_image.png',
  photographer_image: '/images/photographer_image.png',
  hero_image: '/images/hero_image.png',
};
